# Generated by Django 4.0.6 on 2022-08-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_image_link_listing_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_date',
            field=models.DateTimeField(default='2022-08-06'),
        ),
    ]
