# Generated by Django 4.0.6 on 2022-08-06 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid',
            new_name='current_bid',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='bidder',
            new_name='highest_bidder',
        ),
    ]
