# Generated by Django 4.0.6 on 2022-08-07 00:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listing_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='amount',
            new_name='bid_id',
        ),
        migrations.AlterField(
            model_name='bid',
            name='highest_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='num_bids',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 7, 0, 9, 57, 118777, tzinfo=utc)),
        ),
    ]
