# Generated by Django 4.0.6 on 2022-08-07 00:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_rename_amount_listing_bid_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bid_id',
            new_name='amount_id',
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 7, 0, 17, 14, 73274, tzinfo=utc)),
        ),
    ]
