# Generated by Django 4.0.6 on 2022-08-07 00:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_rename_bid_id_listing_amount_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='amount_id',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 7, 0, 19, 55, 853589, tzinfo=utc)),
        ),
    ]
