# Generated by Django 4.0.6 on 2022-08-07 00:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_listing_listing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 7, 0, 22, 43, 657169, tzinfo=utc)),
        ),
    ]
